import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { clashDisplay } from "./fonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={clashDisplay.className}>
      <body className="bg-background text-foreground">{children}</body>
    </html>
  );
}
